[build]
  command = "npm ci --include dev && npm run build && npm prune --omit dev"
  publish = "./api/static"

[dev]
  command = "npm start"

[env]
  DATABASE_URL = "${DATABASE_URL}"
  LOG_LEVEL = "info"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"